### ISSUE TITLE
Forge, errors on load

### ISSUE THREAD

**Issue by Volnovik** [LEv145/sd-webui-ar-plus#30]
Getting following errors when starting forge:

*** Error calling: S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 307, in ui
        self.read_resolutions()
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 259, in read_resolutions
        self.res_labels, res, self.res_comments = parse_resolutions_file(
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 124, in parse_resolutions_file
        label, width, height = line.strip().split(",")
    ValueError: not enough values to unpack (expected 3, got 2)

---
*** Error calling: S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py/ui
    Traceback (most recent call last):
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\modules\scripts.py", line 545, in wrap_call
        return func(*args, **kwargs)
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 307, in ui
        self.read_resolutions()
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 259, in read_resolutions
        self.res_labels, res, self.res_comments = parse_resolutions_file(
      File "S:\StabilityMatrix\Packages\Stable Diffusion WebUI Forge\extensions\--sd-webui-ar-plus\scripts\sd-webui-ar.py", line 124, in parse_resolutions_file
        label, width, height = line.strip().split(",")
    ValueError: not enough values to unpack (expected 3, got 2)

**Update: Error is present when more than certain number of resolutions is present in resolutions.txt**

**Comment by LEv145** [comment]
What is the content of "resolutions.txt" file?

**Comment by Volnovik** [comment]
> What is the content of "resolutions.txt" file?

512, 512, 512     # 512x512
768, 768, 768     # 768x768
1024, 1024, 1024  # 1024x1024
SD3:2, 768, 512
SDXL 3:2, 1216, 832
SDXL 16:9, 1344, 768
SDXL 21:9, 1536, 640
SDXL 5:4, 1152, 896

When I add one more line - it fails and removes whole bar.

**Comment by LEv145** [comment]
I think there may be an empty line at the end of the file:
```
512, 512, 512 # 512x512
768, 768, 768 # 768x768
1024, 1024, 1024 # 1024x1024
SD3:2, 768, 512
SDXL 3:2, 1216, 832
SDXL 16:9, 1344, 768
SDXL 21:9, 1536, 640
SDXL 5:4, 1152, 896
  <- empty line
```

**Comment by Volnovik** [comment]
> I think there may be an empty line at the end of the file:

There is no empty line, but I double checked by adding a line one more time and now everything looks fine. No idea what was the problem since I did not save original config that gave errors. Guess this can be qualified as user error for now.
